<a href="https://colab.research.google.com/github/playeredlc/treinamento-h2ia/blob/master/praticas_numpy_matplotlib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Numpy

## Arrays

**Termos utilizados:**

*Rank* - Número de dimensões do array.

*Shape* - Tupla de inteiros que representa o tamanho do array em cada dimensão.

### Criação e acesso

In [2]:
# np.array pode ser criado a partir de uma list (tipo de dado nativo do python)
rank1_arr = np.array([1, 2, 3])
# no caso de mais dimensões cada elemento da list é uma list.
rank2_arr = np.array([[1, 2, 3], [4, 5 ,6]])

print(f'Rank 1 array. Shape: {rank1_arr.shape}.')
print(rank1_arr)

print(f'\nRank 2 array. Shape: {rank2_arr.shape}.')
print(rank2_arr)

# acesso e modificação de elemento específico
print('\nAcesso ao elemento lin: 1, col: 2:')
print(rank2_arr[1, 2])

print('Atribuição de novo valor:')
rank2_arr[1, 2] = 0
print(rank2_arr[1, 2])

print(f'\nRank 2 array:')
print(rank2_arr)


Rank 1 array. Shape: (3,).
[1 2 3]

Rank 2 array. Shape: (2, 3).
[[1 2 3]
 [4 5 6]]

Acesso ao elemento lin: 1, col: 2:
6
Atribuição de novo valor:
0

Rank 2 array:
[[1 2 3]
 [4 5 0]]


### Métodos de inicialização

In [3]:
# diferentes métodos de inicialização de numpy.arrays

# array preenchido com 0 em todas as posições
arr = np.zeros((2, 3))
print(f'Zeros:\n{arr}\n')

# array preenchido com 1 em todas as posições
arr = np.ones((2, 3))
print(f'Ones:\n{arr}\n')

# array preenchido com uma constante
arr = np.full((2, 3), 1.23)
print(f'Full (constante):\n{arr}\n')

# array preenchido com valores aleatórios (0 - 1)
arr = np.random.random((2, 3))
print(f'Random:\n{arr}\n')

# matriz identidade de nxn dimensões
n = 3
arr = np.eye(n)
print(f'Eye (matriz identidade):\n{arr}')

Zeros:
[[0. 0. 0.]
 [0. 0. 0.]]

Ones:
[[1. 1. 1.]
 [1. 1. 1.]]

Full (constante):
[[1.23 1.23 1.23]
 [1.23 1.23 1.23]]

Random:
[[0.49352304 0.99540429 0.39695478]
 [0.7884413  0.96383833 0.86903411]]

Eye (matriz identidade):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Indexação

#### Slicing

Utilizar slicing permite indexar um sub-array do array original, definindo um intervalo específico de linhas e colunas a ser indexado.

In [4]:
# SLICING

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13, 14, 15, 16]])
print('Array original')
print(arr, '\n')


print('2 primeiras linhas e 3 primeiras colunas')
print(arr[:2, :3], '\n')

print('indexar a partir da segunda linha e segunda coluna (ignorando a primeira)')
print(arr[1:, 1:], '\n')

print('ignorar primeiras e últimas colunas.')
print(arr[1:arr.shape[0]-1, 1:arr.shape[1]-1], '\n')

print('modificações afetam o array original')
arr[1:arr.shape[0]-1, 1:arr.shape[1]-1] = 0

print(arr, '\n')

Array original
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

2 primeiras linhas e 3 primeiras colunas
[[1 2 3]
 [5 6 7]] 

indexar a partir da segunda linha e segunda coluna (ignorando a primeira)
[[ 6  7  8]
 [10 11 12]
 [14 15 16]] 

ignorar primeiras e últimas colunas.
[[ 6  7]
 [10 11]] 

modificações afetam o array original
[[ 1  2  3  4]
 [ 5  0  0  8]
 [ 9  0  0 12]
 [13 14 15 16]] 



#### Utilizando inteiros

Utilizando inteiros para fazer a indexação, é possível selecionar elementos arbitrários do array original a serem utilizados na construção de outros.


In [5]:
# UTILIZANDO INTEIROS

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13, 14, 15, 16]])
print('Array original')
print(arr, '\n')

# os elementos com mesmo índice nas 2 duas listas representam os valores para linha e coluna
print('acessando os elementos da diagonal principal:')
print(arr[[0,1,2,3], [0,1,2,3]], '\n')

# é possível 'filtrar' um elemento de cada linha utilizando uma lista de indices
index_list = [0, 1, 2, 3]
print('acessando diagonal principal com lista de indices:')
print(arr[np.arange(4), index_list], '\n')

# da mesma forma é possível modificar os elementos
arr[np.arange(4), index_list] = 0
print('zerando a diagonal principal:')
print(arr, '\n')


Array original
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

acessando os elementos da diagonal principal:
[ 1  6 11 16] 

acessando diagonal principal com lista de indices:
[ 1  6 11 16] 

zerando a diagonal principal:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]] 



#### Utilizando booleanos

O uso de booleanos permite indexar elementos arbitrários do array que satisfaçam uma determinada condição lógica.

In [6]:
# UTILIZANDO BOOLEAN

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13, 14, 15, 16]])
print('Array original')
print(arr, '\n')

print('elementos > 5 recebem o valor True')
print(arr > 5, '\n')

print('elementos pares recebem o valor True:')
print(arr%2 == 0, '\n')

print('utilizando o array resultante obter os valores reais:')
print(arr[arr%2==0], '\n')


Array original
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

elementos > 5 recebem o valor True
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]] 

elementos pares recebem o valor True:
[[False  True False  True]
 [False  True False  True]
 [False  True False  True]
 [False  True False  True]] 

utilizando o array resultante obter os valores reais:
[ 2  4  6  8 10 12 14 16] 



### Operações Matemáticas

As operações matemáticas realizadas nos arrays são feitas elemento a elemento e podem ser utilizadas por meio dos operadores convencionais (existe sobrecarga de operadores) ou utilizando os métodos disponíveis para objetos do tipo array. O módulo do numpy também implementa diversas operações úteis como funções, uma delas é a função *sum()* vista abaixo.


In [7]:
# função sum() do módulo numpy

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13, 14, 15, 16]])
print('Array original')
print(arr, '\n')

print('Soma de todos os elementos do array:')
print(np.sum(arr), '\n')

print('Soma de todos os elementos POR LINHA:')
print(np.sum(arr, axis=1), '\n')

print('Soma de todos os elementos POR COLUNA:')
print(np.sum(arr, axis=0), '\n')

Array original
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

Soma de todos os elementos do array:
136 

Soma de todos os elementos POR LINHA:
[10 26 42 58] 

Soma de todos os elementos POR COLUNA:
[28 32 36 40] 



In [8]:
# multiplicação de matrizes

arr = np.array([[1,2], [3,4]])
print('Array original')
print(arr, '\n')

print('Multiplicação elemento a elemento')
print(arr * arr, '\n')
# ou
print(np.multiply(arr, arr), '\n')

# para realizar o produto de matrizes de fato utiliza-se o método dot(print(arr.dot(arr), '\n')
print(arr.dot(arr), '\n')
# ou
print(np.dot(arr, arr), '\n')

Array original
[[1 2]
 [3 4]] 

Multiplicação elemento a elemento
[[ 1  4]
 [ 9 16]] 

[[ 1  4]
 [ 9 16]] 

[[ 7 10]
 [15 22]] 

[[ 7 10]
 [15 22]] 



### Broadcasting

Esse termo diz respeito a forma com que o numpy realiza operações elemento a elemento quando os arrays envolvidos não possuem o mesmo shape.

Esse mecanismo permite que essas operações com matrizes sejam vetorizadas e sejam executadas em C ao invés de Python, gerando um ganho de performance. A forma com que é implementado também garante que não haja uso desnecessário de memória com dados redundantes, caso os shapes dos arrays envolvidos atendam a algumas regras de compatibilidade.

In [9]:
# exemplo de soma elemento a elemento onde os arrays são compatíveis

bigger_arr = np.array([[0, 0, 0],
                         [10, 10, 10],
                         [20, 20, 20],
                         [30, 30, 30]])
print(f'Array maior. Shape: {bigger_arr.shape}')
print(bigger_arr, '\n')

smaller_arr = np.array([1, 2, 3])
print(f'Array menor. Shape: {smaller_arr.shape}')
print(smaller_arr, '\n')

# a soma ocorre normalmente
print('bigger + smaller:')
print(bigger_arr + smaller_arr, '\n')


print('---')
# exemplo de array incompatível
smaller_arr_incomp = np.array([1,2,3,4])

print(f'Array menor incompatível. Shape: {smaller_arr_incomp.shape}', '\n')

print('bigger + smaller (incompatibles):', '\n')
try:
  print(bigger_arr + smaller_arr_incomp)
except Exception as e:
  print('Ocorreu um erro:')
  print(e)


Array maior. Shape: (4, 3)
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]] 

Array menor. Shape: (3,)
[1 2 3] 

bigger + smaller:
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]] 

---
Array menor incompatível. Shape: (4,) 

bigger + smaller (incompatibles): 

Ocorreu um erro:
operands could not be broadcast together with shapes (4,3) (4,) 
